name: PHP Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        # Add additional PHP versions if you want to test against them
        include:
          - php-versions: '8.2'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, json, pdo, pdo_mysql
        coverage: xdebug

    - name: Install dependencies with Composer
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --verbose
      env:
        APP_ENV: testing

    - name: Check code style with PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: tests/coverage-report/